void b_0(){printf("It is b_0\n");}
void b_1(){printf("It is b_1\n");}
void b_2(){printf("It is b_2\n");}
void b_3(){printf("It is b_3\n");}
void b_4(){printf("It is b_4\n");}
void b_5(){printf("It is b_5\n");}
void b_6(){printf("It is b_6\n");}
void b_7(){printf("It is b_7\n");}
void b_8(){printf("It is b_8\n");}
void b_9(){printf("It is b_9\n");}
void b_10(){printf("It is b_10\n");}
void b_11(){printf("It is b_11\n");}
void b_12(){printf("It is b_12\n");}
void b_13(){printf("It is b_13\n");}
void b_14(){printf("It is b_14\n");}
void b_15(){printf("It is b_15\n");}
void b_16(){printf("It is b_16\n");}
void b_17(){printf("It is b_17\n");}
void b_18(){printf("It is b_18\n");}
void b_19(){printf("It is b_19\n");}
void b_20(){printf("It is b_20\n");}
